export const IS_LOGGED_OUT = "IS_LOGGED_OUT";
export const IS_LOGGED_IN = "IS_LOGGED_IN";

export const MODAL_OPEN= "MODAL_OPEN";
export const MODAL_CLOSE= "MODAL_CLOSE";

export const ERROR_MODAL_CLOSE= "ERROR_MODAL_CLOSE";
export const ERROR_MODEL_OPEN = "ERROR_MODEL_OPEN";

export const LOADING_STARTED= "LOADING_STARTED";
export const LOADING_COMPLETE= "LOADING_COMPLETE";

export const SEARCH_PATIENT= "SEARCH_PATIENT";
export const VIEW_PATIENT= "VIEW_PATIENT";
export const CLEAR_SEARCH_PATIENT= "CLEAR_SEARCH_PATIENT";
export const POPULATE_PATIENTS="POPULATE_PATIENTS";
export const ADD_PATIENT= "ADD_PATIENT";
export const ALL_PATIENT= "ALL_PATIENT";
export const ADD_BLOOD_REPORT= "ADD_BLOOD_REPORT";
export const ADD_INITIAL_DIAGNOSIS= "ADD_INITIAL_DIAGNOSIS";
export const ADD_DAILY_DIAGNOSIS= "ADD_DAILY_DIAGNOSIS";
export const ADD_ADMISSION= "ADD_ADMISSION";

export const UPDATE_PATIENT= "UPDATE_PATIENT";
export const UPDATE_BLOOD_REPORT= "UPDATE_BLOOD_REPORT";
export const UPDATE_INITIAL_DIAGNOSIS= "UPDATE_INITIAL_DIAGNOSIS";
export const UPDATE_DAILY_DIAGNOSIS= "UPDATE_DAILY_DIAGNOSIS";
export const UPDATE_ADMISSION= "UPDATE_ADMISSION";

export const DELETE_PATIENT= "DELETE_PATIENT";
export const DELETE_BLOOD_REPORT= "DELETE_BLOOD_REPORT";
export const DELETE_INITIAL_DIAGNOSIS= "DELETE_INITIAL_DIAGNOSIS";
export const DELETE_DAILY_DIAGNOSIS= "DELETE_DAILY_DIAGNOSIS";
export const DELETE_ADMISSION= "DELETE_ADMISSION";
